name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frontend:${{ github.sha }} --tag frontend:latest

    - name: List Docker images
      run: docker images

    - name: Push the Docker image to Docker Hub
      run: |
        docker push <your-dockerhub-username>/frontend:${{ github.sha }}
        docker push <your-dockerhub-username>/frontend:latest
